query AdDetails($adId: Int!) {
  getAdById(adId: $adId) {
    id
    title
    description
    owner {
      id
      nickname
      avatar
    }
    price
    location
    picture
    category {
      id
      name
    }
    tags {
      id
      name
    }
  }
}
