mutation AuthWebAuthnCredentialOptions($username: String!) {
  authWebAuthnCredentialOptions(username: $username) {
    challenge
    rpId
    timeout
    allowCredentials {
      id
      transports
      type
    }
    extensions {
      appid
      hmacCreateSecret
      credProps
    }
    userVerification
  }
}
