mutation AuthWebAuthnCredential(
  $credential: CredentialAuthInput!
  $challenge: String!
  $username: String!
) {
  authWebAuthnCredential(
    credential: $credential
    challenge: $challenge
    username: $username
  )
}
