mutation RegisterWebAuthnCredential(
  $challenge: String!
  $credential: CredentialInput!
  $username: String!
  $displayname: String!
) {
  registerWebAuthnCredential(
    challenge: $challenge
    credential: $credential
    username: $username
    displayname: $displayname
  )
}
