mutation SignupPasswordlessOptions($displayname: String!, $username: String!) {
  signupPasswordlessOptions(displayname: $displayname, username: $username) {
    rp {
      id
      name
    }
    user {
      displayName
      id
      name
    }
    challenge
    pubKeyCredParams {
      alg
      type
    }
    timeout
    excludeCredentials {
      type
      id
      transports
    }
    authenticatorSelection {
      authenticatorAttachment
      requireResidentKey
      residentKey
      userVerification
    }
    attestation
    extensions {
      appid
      credProps
      hmacCreateSecret
    }
  }
}
