services:
  db:
    stop_grace_period: 0s
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  backend:
    stop_grace_period: 0s
    environment:
      DB_HOST: db
      KVSTORE_HOST: ${KVSTORE_HOST:-kvStore}
    depends_on:
      db:
        condition: service_healthy
    build: backend
    ports:
      - 4001:4001
    volumes:
      - ./backend/src:/app/src

  upload-service:
    stop_grace_period: 0s
    build: file-upload-service
    ports:
      - 8000:8000
    volumes:
      - ./file-upload-service/files:/app/files

  frontend:
    stop_grace_period: 0s
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src

  kvStore:
    image: valkey/valkey:7.2.5-alpine3.19
    stop_grace_period: 0s
    command: valkey-server --save 1 1 --loglevel warning
    volumes:
      - devKVStore:/data

volumes:
  devKVStore:
