services:
  db:
    image: postgres:15-alpine
    stop_grace_period: 0s
    environment:
      POSTGRES_PASSWORD: ${DB_PASS-postgres}
      PGUSER: ${DB_USER-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - prodDB:/var/lib/postgresql/data

  backend:
    stop_grace_period: 0s
    env_file: backend/.env
    environment:
      DB_HOST: db
      DB_PASS: ${DB_PASS-postgres}
      DB_USER: ${DB_USER-postgres}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY:-changeme}
      NODE_ENV: ${NODE_ENV:-production}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-changeme}
    depends_on:
      db:
        condition: service_healthy
    build:
      context: backend
      dockerfile: Dockerfile.production

  frontend:
    environment:
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY:-changeme}
    stop_grace_period: 0s
    env_file: frontend/.env
    build:
      context: frontend
      dockerfile: Dockerfile.production

  upload-service:
    environment:
      - HOST=/
    stop_grace_period: 0s
    build: file-upload-service
    volumes:
      - prodUploads:/app/files

  gateway:
    restart: always
    stop_grace_period: 0s
    build:
      context: gateway
      dockerfile: Dockerfile.production
    ports:
      - ${GATEWAY_PORT-80}:80
    
volumes:
  prodDB:
  prodUploads:
