POST http://localhost:4000/ads
Content-Type: application/json

{
    "title": "Mon annonce 2",
    "description": "My bike is blue, working fine. I'm selling it because I've got a new one",
    "owner": "bike.seller@gmail.com",
    "price": 100,
    "picture": "https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
    "location": "Paris",
    "category": 1,
    "tags": [{"id": 1}, {"id": 3}]
}