import Head from "next/head";
import Header from "@/components/Header";
import RecentAds from "@/components/RecentAds";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <RecentAds />
    </>
  );
}
