name: "integration-tests"

on:
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Make envfile
        run: cp .env.example .env
      - name: Install deps
        run: npm ci
      - name: Start test DB
        run: npm run testDB:wait
      - name: Run tests
        run: npm test
